# Generated by Django 3.1.2 on 2020-10-26 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.UUIDField(default=uuid.uuid4, help_text='Indique el ID del Autor de Noticia', primary_key=True, serialize=False)),
                ('nom_autor', models.TextField(max_length=50)),
                ('educacion', models.CharField(choices=[('UV', 'Universidad'), ('TC', 'Tecnico Profesional'), ('SC', 'Secundaria Completa'), ('NA', 'Ninguno')], default='NA', max_length=2)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('correo', models.EmailField(error_messages={'Error': 'Digite un formato válido!'}, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id_consola', models.UUIDField(default=uuid.uuid4, help_text='Indique el ID de la Noticia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('generacion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_postulacion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('area_postular', models.CharField(choices=[('NV', 'Noticias Videojuegos'), ('NC', 'Noticias Consolas'), ('PG', 'Publicidad Gaming')], default='NV', max_length=2)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
                ('correo', models.EmailField(error_messages={'Error': 'Digite un formato válido!'}, max_length=50)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nivel_estudios', models.CharField(choices=[('UV', 'Universidad'), ('TC', 'Tecnico Profesional'), ('SC', 'Secundaria Completa'), ('NA', 'Ninguno')], default='NA', max_length=2)),
                ('motivo', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.UUIDField(default=uuid.uuid4, help_text='Indique el ID de la Noticia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('tipo_de_noticia', models.CharField(help_text='Debe indicar el tipo de noticia, por ejemplo novedad, popular etc.', max_length=50)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_Noticias.autor')),
            ],
        ),
    ]
