# Generated by Django 3.1.2 on 2020-11-03 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPostular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_postular', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['area_postular'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducacional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educacional', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['nivel_educacional'],
            },
        ),
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['id_postulacion']},
        ),
        migrations.AlterField(
            model_name='autor',
            name='correo',
            field=models.EmailField(error_messages={'Error': 'Digite un formato válido!'}, help_text='Indique el correo del Autor', max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_autor',
            field=models.UUIDField(default=uuid.uuid4, help_text='Indique el ID del Autor de noticia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nom_autor',
            field=models.CharField(help_text='Indique el nombre del Autor', max_length=25),
        ),
        migrations.AlterField(
            model_name='autor',
            name='numero',
            field=models.IntegerField(blank=True, help_text='Indique el número de contacto del Autor', null=True),
        ),
        migrations.AlterField(
            model_name='consola',
            name='generacion',
            field=models.CharField(help_text='Indique la Generación a la que pertenece la Consola', max_length=25),
        ),
        migrations.AlterField(
            model_name='consola',
            name='nombre',
            field=models.CharField(help_text='Indique el Nombre de la Consola', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='apellido',
            field=models.CharField(help_text='Indique los apellidos del postulante', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='correo',
            field=models.EmailField(error_messages={'Error': 'Digite un formato válido!'}, help_text='Indique el correo del postulante', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='motivo',
            field=models.TextField(help_text='Motivo por el cual quiere ser parte del equipo', max_length=500),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(help_text='Indique el nombre del postulante', max_length=50),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='numero',
            field=models.IntegerField(blank=True, help_text='Indique el número de contacto del postulante', null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descripcion',
            field=models.TextField(help_text='Agrege una pequeña descripción de la noticia', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tipo_de_noticia',
            field=models.CharField(help_text='Debe indicar el tipo de noticia, por ejemplo novedad, popular etc.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(help_text='Indique el titular de la noticia', max_length=50),
        ),
        migrations.AlterField(
            model_name='autor',
            name='educacion',
            field=models.ForeignKey(blank=True, help_text='Indique el nivel de estudios de Autor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_Noticias.niveleducacional'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='area_postular',
            field=models.ForeignKey(blank=True, help_text='Indique el Areal a Postular', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_Noticias.areapostular'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nivel_estudios',
            field=models.ForeignKey(blank=True, help_text='Indique el nivel de estudios del postulante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_Noticias.niveleducacional'),
        ),
    ]
