# Generated by Django 3.1.2 on 2020-11-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0003_auto_20201120_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['id_noticia']},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='bajadaimagen1',
            new_name='bajadaimagen',
        ),
    ]
