# Generated by Django 3.1.2 on 2020-11-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0004_auto_20201120_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='parrafo1',
            field=models.TextField(default=' ', help_text='Primer parrafo de la noticia', max_length=500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='portada',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Imagen que se mostrara como portada', upload_to=''),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(default=' ', help_text='Indique el subtitulo de la noticia', max_length=50),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(default=' ', help_text='Indique el titular de la noticia', max_length=50),
        ),
    ]
