# Generated by Django 3.1.2 on 2020-11-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0006_auto_20201120_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='parrafo1',
            field=models.TextField(default=' ', help_text='Primer parrafo de la noticia', max_length=900),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='parrafo2',
            field=models.TextField(help_text='Segundo parrafo de la noticia opcional', max_length=900, null=True),
        ),
    ]
