# Generated by Django 3.1.2 on 2020-11-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Noticias', '0007_auto_20201120_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='bajadaimagen',
            field=models.CharField(help_text='Descripcion de la imagen', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='parrafo1',
            field=models.TextField(default=' ', help_text='Primer parrafo de la noticia', max_length=1500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='parrafo2',
            field=models.TextField(help_text='Segundo parrafo de la noticia opcional', max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(default=' ', help_text='Indique el subtitulo de la noticia', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(default=' ', help_text='Indique el titular de la noticia', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='video',
            field=models.CharField(blank=True, help_text='Link del video que se quiera mostrar (Debe ser en formato EMBED)', max_length=200, null=True),
        ),
    ]
